config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  resources :microposts, only: [:create, :destroy]

  #get 'static_pages/home'

  #get 'static_pages/help'

  #get 'static_pages/about'

  root to: 'static_pages#home'

  match '/about', to: 'static_pages#about', via: [:get]
  
  match '/help', to: 'static_pages#help', via: [:get]

  match '/denied', to: 'static_pages#denied', via: [:get]

  # get the sign up form
  match '/signup', to: 'users#new', via: [:get]
  # create new user using info from form
  match '/users', to: 'users#create', via: [:post]

  match '/signin', to: 'sessions#new', via: [:get]
  match '/signout', to: 'sessions#destroy', via: [:delete]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
	belongs_to :user

	validates(:user_id, presence: true)
	validates :content, presence: true, length: {maximum: 140}

	scope :reversed, -> { order 'microposts.created_at DESC' }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string
#  email           :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string
#  remember_token  :string
#

class User < ApplicationRecord

	# inbuilt rails function to authenticate passwords and 
	# checks with password_digest column in db. Col name predefined
	# has built in authenticate function to authenticate user with
	# supplied password
	has_secure_password
	# one user has many microposts which are destroyed
	# when the user is destroyed
	has_many :microposts, dependent: :destroy

	before_save { |user| user.email = email.downcase }
	before_save :create_remember_token

	validates(:name, presence: true, length: {maximum: 50})
	validates :email, presence: true, uniqueness: { case_sensitive: false}
	validates :password, presence: true, length: {minimum: 6}
	validates :password_confirmation, presence: true

	def feed
		microposts
	end

	private
		def create_remember_token
			self.remember_token = SecureRandom.urlsafe_base64
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
	#since no actions specified, applies to all
	before_filter :get_signed_in_user

	def create
		@micropost = current_user.microposts.build(micropost_params)
		if @micropost.save
			flash[:success] = "Tweeted!"
			redirect_to root_path
		else
			render 'static_pages/home'
		end
	end

	def destroy
		
	end

	private
		def micropost_params
			params.require(:micropost).permit(:content)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		# same as params(session(email)). i.e. params is a hashset
		# of session, and session is a hashset of emails and passwords
		user = User.find_by_email(params[:session][:email])
		# all objects in ruby are true other than false and nil
		# hence if user.authenticate returns true, and a valid user, then
		# if condition is true
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_back_or root_path
		else
			# flash only gets called on the first request.
			# but render isnt a request, hence flash is called twice currently
			# hence flash.now is used
			#flash[:error] = 'Invalid email/password combo'
			flash.now[:error] = 'Invalid email/password combo'
			# renders new.html sign in form
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_path
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if signed_in?
  		@micropost = current_user.microposts.build
  		@feed_items = current_user.feed.paginate(page: params[:page])
  	end
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before filter makes the particular method here make user sign in
  # to be executed before every action.
  # only applies filter only to the specified actions
  before_filter :make_user_sign_in, only: [:edit, :update, :index]
  before_filter :correct_user, only: [:edit, :update]
  before_filter :get_signed_in_user, only: [:edit, :update]

  # renders the signup form, using the new file in view/users/new
  def new
    # empty instance used in the new view
    @user = User.new
  end

  def show
  	@user = User.find_by_id(params[:id])
    @microposts = @user.microposts.paginate page: params[:page]
  end

  # creates new user from form's params
  def create
  	@user = User.new(user_params)
    #@user = User.new(params[:user])
  	if @user.save
      sign_in @user
      flash[:success] = "Welcome to Sample App!"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  # render the edit page
  def edit
    # in view when constructing form using form_for
    # rails uses POST if @user.new_record? is true
    # and PUT otherwise
    @user = User.find_by_id(params[:id])
  end

  def update
    @user = User.find(params[:id])
    # update_attributes(params[:user]) not working
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  private
  # strong parameters
  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def make_user_sign_in
    # same as flash[:notice] = "Please sign in."
    # redirect_to signin_path
    redirect_to signin_path, notice: "Please sign in." unless signed_in?
  end

  def correct_user
    @user = User.find_by_id(params[:id])
    redirect_to(denied_path) unless current_user?(@user)
  end

  #def get_signed_in_user
  #  unless signed_in?
  #    store_location
  #    redirect_to signin_path, notice: "Please sign in"
  #  end
  #end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
		base_title = "Ruby on Rails Sample App"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end

	def user_name_title(page_title)
		if page_title.empty?
			"Profile Page"
		else
			page_title
		end
	end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		cookies.permanent[:remember_token] = user.remember_token
		self.current_user = user
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		@current_user ||= User.find_by_remember_token(cookies[:remember_token])
	end

	def current_user?(user)
		user == current_user
	end

	def signed_in?
		!current_user.nil?
	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end

	# for friendly forwarding..redirecting unsigned user
	# to their profile when edit is clicked
	def redirect_back_or(default)
		# session hashset built in in rails..instance of
		# cookies variable in browser which expires upon
		# browser close
		# rediects to session[:return_to] URL if it exists
		# or default otherwise
		redirect_to(session[:return_to] || default)
		# deleted because future sign ins should not redirect
		# to other user's page
		session.delete(:return_to)
	end

	# for friendly forwarding
	def store_location
		session[:return_to] = request.fullpath
	end

	def get_signed_in_user
		unless signed_in?
			store_location
			redirect_to signin_path, notice: "Please sign in"
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	#returns the Gravatar
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://www.gravatar.com/avatar/#{gravatar_id}.png"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end

	def image_for(user)
		if user.id == 2
			image_url = "http://orig02.deviantart.net/a56c/f/2012/026/0/7/render__naruto_by_naruhinabrazil-d4norui.png"
			#image_tag(image_url, alt: user.name, class:"gravatar")
		elsif user.id == 1
			image_url = 'https://pbs.twimg.com/profile_images/647507270029418501/v0FpaptX.jpg'
			#image_tag(image_url, alt: user.name, class: "gravatar")
		else
			image_url = 'http://wallpaper.sc/en/ipad/wp-content/uploads/2014/10/ipad-2048x2048-thumbnail_00908-256x256.jpg'
			#image_tag(image_url, alt: user.name, class: "gravatar")
		end
		image_tag(image_url, alt: user.name, class: "gravatar")
	end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		Rails sample app by Naruto Uzumaki
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Help", help_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top">
	<div class="navbar-inner">
		<%= link_to "sample app", root_path, id: "logo", style: "margin-left: 15px" %>
		<nav>
			<% if signed_in? %>
				<ul class="nav navbar-nav" style="margin-left:40%">
			<% else %>
				<ul class="nav navbar-nav">
			<% end %>
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "About", about_path %></li>
        		<li><%= link_to "Help", help_path %></li>
        		<% if signed_in? %>
        			<li><%= link_to "Users", users_path %></li>
        			<li class="dropdown" style="margin-top:10px">
        				<button class="btn btn-default dropdown-toggle" type="button" id="dropDownMenu1" data-toggle="dropdown">
        					Account
        					<span class="caret"></span>
        				</button>
        				<ul class="dropdown-menu" aria-labelledby="dropDownMenu1">
	        				<li><%= link_to "Profile", current_user %></li>
	        				<li><%= link_to "Settings",edit_user_path(current_user) %></li>
	        				<li role="separator" class="divider"></li>
	        				<li><%= link_to "Sign out", signout_path, method: "delete" %></li>
        				</ul>
        			</li>
        			<% else %>
						<li><%= link_to "Sign in", signin_path %></li>
					<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  	<%= render 'layouts/header' %>
  	<div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    	<%= yield %>
    	<%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<li>
	<span class="content">
		<%= micropost.content %>
	</span>
	<span class="timestamp">
		Posted <%= time_ago_in_words(micropost.created_at) %>
	</span>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			This form contains <%= pluralize(object.errors.count, "error") %>
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="microposts">
		<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ol>
	<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
	<span class="user">
		<%= link_to feed_item.user.name, feed_item.user %>
	</span>
	<span class="content"><%= feed_item.content %></span>
	<span class="timestamp">
		Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
	</span>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
<!-- passing a hash of object to error messages makes a variable object in the error messages partial which can be used to access errors associated with the given object type -->
	<%= render 'shared/error_messages', object: f.object %>
	<div>
		<%= f.text_area :content, placeholder: "Compose new tweet...", style: "width: 100%; height: 120px; border: 1px solid #c8c8c8; border-radius: 2%" %>	
	<%= f.submit "Post", class: "btn btn-large btn-primary" %>
	</div>
<% end %>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
	<%= image_for(current_user) %>
</a>
<h1 style="margin-bottom: 10px;">
	<%= current_user.name %>
</h1>
<span style="margin-bottom: 5px;">
	<%= link_to "View my profile", current_user %>
</span>
<span style="color: #555555">
	<%= pluralize(current_user.microposts.count, "Tweet") %>
</span>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>Welcome to about us section</p>

app/views/static_pages/denied.html.erb
<h1>
	You tried being naughty!!
</h1>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
	<div class="row">
		<aside class="col-md-4">
			<section>
				<%= render 'shared/user_info' %>
			</section>
			<section>
				<%= render 'shared/micropost_form' %>
			</section>
		</aside>
		<div class="col-md-8">
			<h3 style="margin-left:40px">News Feed</h3>
			<%= render 'shared/feed' %>
		</div>
	</div>
<% else %>
	<div class="center hero-unit">
		<h1>Welcome to Sample App</h1>
		<h2>Home page for sample app</h2>

		<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
	</div>

	<%= link_to image_tag("itachi.png", alt: "Mangekyo"), 'http://naruto.wikia.com/wiki/Mangeky%C5%8D_Sharingan', target: "_blank" %>
<% end %>

app/views/users/_user.html.erb
<!-- render method checks for the class of the object on which it is being called. hence here, it renders _user page, since User class object is passed to render -->
<li>
	<%= image_for user %>
	<%= link_to user.name, user %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="form-group">
	<%= form_for(@user) do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
		<%= f.label :name %>
		<%= f.text_field :name, class: "form-control" %>

		<%= f.label :email %>
		<%= f.text_field :email, class: "form-control" %>

		<%= f.label :password %>
		<%= f.password_field :password, class: "form-control" %>

		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation, class: "form-control" %>

		<%= f.submit "Save changes", class: "btn btn-large btn-primary", style: "margin-top: 10px" %>
		<% end %>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
	<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<h1>Sign Up</h1>

<div class="form-group">
	<%= form_for(@user) do |f| %>
		<%= render 'shared/error_messages', object: f.object %>

		<%= f.label :name %>
		<%= f.text_field :name, class: "form-control" %>

		<%= f.label :email %>
		<%= f.text_field :email, class: "form-control" %>

		<%= f.label :password %>
		<%= f.password_field :password, class: "form-control" %>

		<%= f.label :password_confirmation, "Confirmation" %>
		<%= f.password_field :password_confirmation, class: "form-control" %>

		<%= f.submit "Create my account", class: "btn btn-large btn-primary", style: "margin-top: 10px" %>
	<% end %>
</div>

app/views/users/show.html.erb
<div class="row">
	<aside class="col-md-4">
		<section>
			<h1>
				<%= image_for @user %>
				<%= @user.name %>
			</h1>		
		</section>
	</aside>
	<div class="col-md-8">
		<% if @user.microposts.any? %> 
		<h3>Tweets (<%= @user.microposts.count %>)</h3>
		<ol class="microposts">
			<%= render partial: 'microposts/micropost', collection: @microposts.reverse %>
		</ol>
		<%= will_paginate @microposts %>
		<% end %>
	</div>
</div>